### ISSUE TITLE
Make the CI report coverage

### ISSUE THREAD

**Issue by ljmf00** [codacy/csharp-codacy-coverage#3]

**Comment by kreghek** [comment]
I do not sure what I am writing to that task. But doing coverage collection on a build server does not send data to Codacy.

This is build server log. Look like all OK https://circleci.com/gh/kreghek/Zilon_Roguelike/3063
This is Codacy dashboard. No coverage https://app.codacy.com/manual/kreghek/Zilon_Roguelike/dashboard
What I am doing wrong&

**Comment by lolgab** [comment]
Closing since this repository is archived and the reporter deprecated in favor of https://github.com/codacy/codacy-coverage-reporter
